### ISSUE TITLE
from computer_vision_utils.stitching import stitch_together

### ISSUE THREAD

**Issue by yizhiweimengxiangfendoudefeifei** [ndrplz/self-driving-car#16]
i can't find computer_vision_utils.stitching ! please help me

**Comment by ndrplz** [comment]
Hi @yizhiweimengxiangfendoudefeifei ,

the reference is to [this](https://github.com/ndrplz/computer_vision_utils) repository.

I'll leave the issue open to remember to move that function to the self-driving-car repo to avoid future mixups.

**Comment by yizhiweimengxiangfendoudefeifei** [comment]
thanks, i have found it. thanks a lot.
