### ISSUE TITLE
How to run project 3 with my own images and control

### ISSUE THREAD

**Issue by ArtlyStyles** [ndrplz/self-driving-car#18]
I would like to run Project 3 - Behavioral Cloning but with my own images and control. How can I do it? It was not very clear which is the training steep, and which is the inference step. Also, what is the best way to replace the data with my own images and control? My control data also have throttle data, but I can start with just steering.

**Comment by ndrplz** [comment]
> It was not very clear which is the training steep, and which is the inference step.

The training code is [here](https://github.com/ndrplz/self-driving-car/blob/1eadaca5e39b0448385db7ac2de0732d6dd7e600/project_3_behavioral_cloning/model.py#L66-L89). Inference step (i.e. actually driving in the simulator) is in [`drive.py`](https://github.com/ndrplz/self-driving-car/blob/master/project_3_behavioral_cloning/drive.py).

> Also, what is the best way to replace the data with my own images and control?

As you can see from the training code, I relied on a [generator](https://github.com/ndrplz/self-driving-car/blob/1eadaca5e39b0448385db7ac2de0732d6dd7e600/project_3_behavioral_cloning/model.py#L84) to provide training examples. This is implemented [here](https://github.com/ndrplz/self-driving-car/blob/1eadaca5e39b0448385db7ac2de0732d6dd7e600/project_3_behavioral_cloning/load_data.py#L60-L136) currenty [returns only the couple *(image, steering_angle)*](https://github.com/ndrplz/self-driving-car/blob/1eadaca5e39b0448385db7ac2de0732d6dd7e600/project_3_behavioral_cloning/load_data.py#L136) but it can be modified to return the throttle too if that is available. It should be fairly easy to generate a CSV file similar to [this one](https://raw.githubusercontent.com/ndrplz/self-driving-car/master/project_3_behavioral_cloning/data/driving_log.csv), but pointing to your own data. With minor code refactoring you should be able to train on your dataset.

**Comment by ArtlyStyles** [comment]
I would like to try Udacity data first. How can I load their data?

**Comment by ndrplz** [comment]
You can record Udacity data through their [simulator](https://github.com/udacity/self-driving-car-sim). If you format the CSV similar to [the one](https://raw.githubusercontent.com/ndrplz/self-driving-car/master/project_3_behavioral_cloning/data/driving_log.csv) in this repo, you should be able to run this code with minor modifications.
