### ISSUE TITLE
Lane / road marking / vanishing point dataset

### ISSUE THREAD

**Issue by SeokjuLee** [ndrplz/self-driving-car#26]
[VPGNet](https://arxiv.org/abs/1710.06288) dataset is available.
It contains around 21K images with human-annotated lane, road markings, and vanishing point labels.
For more details, please check our project [page](https://github.com/SeokjuLee/VPGNet#vpgnet-dataset).

**Comment by ndrplz** [comment]
Closing as it's not the right place for self-promotion
