### ISSUE TITLE
Following datas are needed.

### ISSUE THREAD

**Issue by rezwanulhaquerezwan** [ndrplz/self-driving-car#3]
You have used `train.p`  and `test.p`. But I did not find your repository.
Please, give these datasets.

```
# Load pickled data
train, test = load_traffic_sign_data('../traffic_signs_data/train.p', '../traffic_signs_data/test.p')
```

**Comment by ndrplz** [comment]
Hi @rezwanulhaquerezwan,

these are binary files containing the data, so it's not really convenient to add them to this repository. However, you can download yourself the data from the [German Traffic Sign Dataset](http://benchmark.ini.rub.de/?section=gtsrb&subsection=dataset#Structure).

Best,
A.
